roniemartinez/latex2mathml

.travis.yml, CHANGELOG.md, README.md, setup.py, test-requirements.txt
=> Release 2.4.0

.travis.yml, CHANGELOG.md, README.md, appveyor.yml, setup.py
=> Appveyor integration

.travis.yml, CHANGELOG.md, README.md, appveyor.yml, setup.py
=> CI caching

.travis.yml, CHANGELOG.md, setup.py
=> Travis deploy

CHANGELOG.md, LICENSE, README.md, setup.py
=> [skip ci] 2.6.2

CHANGELOG.md, LICENSE, README.md, setup.py
Reverts Code-ReaQtor/latex2mathml#38
=> Revert "2.6.2"

appveyor.yml
=> [skip ci] Update appveyor.yml

.travis.yml, CHANGELOG.md, poetry.lock, pyproject.toml
- Update .travis.yml
- Update dependencies
=> Remove coverage from dev dependencies

latex2mathml/converter.py, poetry.lock, pyproject.toml, setup.py, tests/test_converter.py
=> Support trigonometric functions

latex2mathml/aggregator.py, latex2mathml/tokenizer.py, poetry.lock, pyproject.toml, setup.py, tests/test_aggregator.py
=> Find match opening parenthesis

latex2mathml/commands.py, latex2mathml/converter.py, poetry.lock, pyproject.toml, setup.py, tests/test_converter.py
=> Add support for \overrightarrow

Makefile, latex2mathml/commands.py, latex2mathml/converter.py, poetry.lock, pyproject.toml, setup.py, tests/test_converter.py
- Fixes #106 
- Add .PHONY
- Update dependencies
=> Fix \cases

latex2mathml/aggregator.py, latex2mathml/tokenizer.py, pyproject.toml, setup.py, tests/test_aggregator.py, tests/test_converter.py, tests/test_tokenizer.py
=> [WIP] Fix bug on \max, \min, etc. operators without param

README.md, README.rst, pyproject.toml, setup.py
=> Move from travis-ci.org to www.travis-ci.com

.github/workflows/codeql-analysis.yml, latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/tokenizer.py, poetry.lock, pyproject.toml, setup.py, tests/test_converter.py, tests/test_tokenizer.py
- Support \text (Resolves #118)
- Support control space
References:
- https://tex.stackexchange.com/questions/3415/what-is-the-correct-way-of-embedding-text-into-math-mode
- https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing
=> Support \text

Makefile, latex2mathml/converter.py, pyproject.toml, setup.py, tests/test_converter.py
=> 🐛 Fix comma should be <mo>

README.md, README.rst, pyproject.toml, setup.py
- Fixes 2.18.3 (https://github.com/roniemartinez/latex2mathml/pull/122)
=> 🛠️ Update README.md

.github/dependabot.yml
=> 💚 [skip ci] Ignore tomlkit

README.md, README.rst, latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/tokenizer.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_tokenizer.py, tests/test_walker.py
=> 🐛 Fix \quad and \qquad, and ✨ add \hspace support

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/exceptions.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
=> ✨ Add support for big commands

latex2mathml/commands.py, poetry.lock, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support negative thin space \!

latex2mathml/commands.py, latex2mathml/tokenizer.py, pyproject.toml, setup.py, tests/test_converter.py
=> 🐛 Fix spaces

latex2mathml/converter.py, latex2mathml/tokenizer.py, poetry.lock, pyproject.toml, setup.py, tests/test_converter.py
=> 🐛 Fix pipe and double pipe

latex2mathml/converter.py, latex2mathml/tokenizer.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_tokenizer.py
- 🚨 Refactor tests for Issue 129
=> 🐛 Fix tilde support

latex2mathml/converter.py, latex2mathml/tokenizer.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_tokenizer.py
=> ✨ Support comments

latex2mathml/commands.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
- 🐛 Fix incorrect nesting on fractions
=> ✨ Support \abovewithdelims

latex2mathml/commands.py, latex2mathml/converter.py, pyproject.toml, setup.py, tests/test_converter.py
- 🐛 Fix \Bbb and global fonts incorrectly setting fonts on other tags
=> ✨ Support \boldsymbol

latex2mathml/symbols_parser.py, pyproject.toml, setup.py, tests/test_converter.py
=> 🎉 Support \centerdot

latex2mathml/symbols_parser.py, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support \diagdown and \diagup

latex2mathml/commands.py, latex2mathml/converter.py, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support \displaylines and \cr

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/tokenizer.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py
- 🔨 Refactor tokenizer pattern
- Related to #161
=> ✨ Support \fbox

latex2mathml/converter.py, latex2mathml/symbols_parser.py, pyproject.toml, setup.py, tests/test_converter.py
- 🐛 Use unicode for > and <
- 🔥 Remove & since it shouldn't be used as operator
=> ✨ Support \gggtr, \gvertneqq and \gt

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/exceptions.py, latex2mathml/tokenizer.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
=> ✨ Support \Huge and \huge

Makefile, latex2mathml/converter.py, latex2mathml/exceptions.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
- 🔥 Remove grouping by parentheses and brackets
- 🔨 Move pytest options to pyproject.toml
=> 🐛 Fix grouping

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/tokenizer.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py
- \kern
- \mskip
- \mspace
- \negthinspace
- \negmedspace
- \negthickspace
- \nobreakspace
- \space
- \thinspace
- Add mu to dimentsions
=> ✨ Support more spaces

latex2mathml/converter.py, latex2mathml/tokenizer.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_tokenizer.py, tests/test_walker.py
=> 🐛 Fix parsing number after subscript and superscript and \math- commands

latex2mathml/commands.py, latex2mathml/converter.py, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support \math- commands

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
=> ✨ Support \phantom, \sideset and \vphantom

latex2mathml/commands.py, latex2mathml/tokenizer.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py
- \mit
- \oldstyle
- \scr
- \tt
- \textbf
- \textit
- \textrm
- \textsf
- \texttt
=> ✨ Support more font command and text style

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/exceptions.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
- 🐛 Fix \hat should be stretchy=false
=> ✨ Support \skew

latex2mathml/commands.py, latex2mathml/converter.py, poetry.lock, pyproject.toml, setup.py
- 🔨 Move \mod and \pmod to _convert_command()
- ⬆️ Update dependencies
=> 🔨 Move \mod and \pmod to _convert_command()

Makefile, README.md, README.rst, poetry.lock, pyproject.toml, setup.py
=> 📚 Fix README

latex2mathml/tokenizer.py, pyproject.toml, setup.py, tests/test_tokenizer.py
=> 🐛 Fix fractions

.github/FUNDING.yml, .github/workflows/python.yml, LICENSE, Makefile, README.md, README.rst, poetry.lock, pyproject.toml, setup.py
=> 📚 Update README

latex2mathml/commands.py, latex2mathml/converter.py, pyproject.toml, setup.py, tests/test_converter.py
Resolves https://github.com/roniemartinez/latex2mathml/issues/293
=> ✨ Support \bmod

README.rst, latex2mathml/converter.py, latex2mathml/exceptions.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
=> 🐛 Fix bug on \limits

latex2mathml/converter.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
- Fixes #307 
- Fix support operator in braces
- Fix empty sides
=> 🐛 Fix bugs on \sideset

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support \overbrace and \underbrace

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
=> ✨ Support \xleftarrow and \xrightarrow

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support \smallmatrix and \bigl, \bigr variants

latex2mathml/tokenizer.py, poetry.lock, pyproject.toml, setup.py, tests/test_tokenizer.py
- 🔨 Simplified tokenizer
- ⬆️ Update dependencies
=> 🔨 Simplified tokenizer

latex2mathml/commands.py, latex2mathml/converter.py, latex2mathml/walker.py, pyproject.toml, setup.py, tests/test_converter.py, tests/test_walker.py
- ✨ Support \not
- 🐛 Fix \operatorname should be <mo>
- Resolves #313
=> ✨ Support \not

latex2mathml/commands.py, latex2mathml/converter.py, pyproject.toml, setup.py, tests/test_converter.py
=> ✨ Support split environment

latex2mathml/commands.py, latex2mathml/converter.py, pyproject.toml, tests/test_converter.py
- ✨ Support align environment
- 🔨 Move columnalign of split environment to individual mtd
- Resolves #312
=> ✨ Support align environment

.github/dependabot.yml, Makefile, pyproject.toml
- Use poetry version --short
- Remove config experimental.new-installer
- Add GitHub Actions to dependabot updates
=> 💚 Use poetry 1.2 commands

README.md, pyproject.toml
https://github.com/badges/shields/issues/8671
=> 🐛 Fix GitHub Actions shield

latex2mathml/tokenizer.py, pyproject.toml, tests/test_tokenizer.py
=> 🐛 Fix \frac
